// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_elec_warn_png);    // assets/elec_warn.png
LV_IMG_DECLARE(ui_img_hazzard_png);    // assets/hazzard.png
LV_IMG_DECLARE(ui_img_left_0_png);    // assets/left_0.png
LV_IMG_DECLARE(ui_img_left_1_png);    // assets/left_1.png
LV_IMG_DECLARE(ui_img_right_0_png);    // assets/right_0.png
LV_IMG_DECLARE(ui_img_right_1_png);    // assets/right_1.png
LV_IMG_DECLARE(ui_img_acc_png);    // assets/acc.png
LV_IMG_DECLARE(ui_img_mppt_png);    // assets/mppt.png
LV_IMG_DECLARE(ui_img_motor_png);    // assets/motor.png
LV_IMG_DECLARE(ui_img_battary_png);    // assets/battary.png
LV_IMG_DECLARE(ui_img_commu_png);    // assets/commu.png
LV_IMG_DECLARE(ui_img_recommend_png);    // assets/recommend.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets/Logo.png

// FONTS
LV_FONT_DECLARE(ui_font_acc);
LV_FONT_DECLARE(ui_font_accunit);
LV_FONT_DECLARE(ui_font_fontspeed);
LV_FONT_DECLARE(ui_font_fontspeedunit);
LV_FONT_DECLARE(ui_font_info);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
