// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_SpeedUnit;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_BattarywarnImage;
extern lv_obj_t * ui_HazzardImage;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_Left0Image;
extern lv_obj_t * ui_Left1Image;
extern lv_obj_t * ui_Right0Image;
extern lv_obj_t * ui_Right1Image;
extern lv_obj_t * ui_AccImage;
extern lv_obj_t * ui_AccUnit;
extern lv_obj_t * ui_AccLabel;
extern lv_obj_t * ui_MpptImage;
extern lv_obj_t * ui_MpptLabel;
extern lv_obj_t * ui_MotorImage;
extern lv_obj_t * ui_MotorLabel;
extern lv_obj_t * ui_BattaryImage;
extern lv_obj_t * ui_BattaryLabel;
extern lv_obj_t * ui_TeleImage;
extern lv_obj_t * ui_FaultcodeLabel;
extern lv_obj_t * ui_RecommedImage;
extern lv_obj_t * ui_RecommendUnit;
extern lv_obj_t * ui_RecommendLabel;
extern lv_obj_t * ui_KustImage;
extern lv_obj_t * ui_info1;
extern lv_obj_t * ui_info2;
extern lv_obj_t * ui_info3;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_info1unit;
extern lv_obj_t * ui_info2unit;
extern lv_obj_t * ui_info3unit;
extern lv_obj_t * ui_FaultcodecountLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

