// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_SpeedUnit = NULL;
lv_obj_t * ui_SpeedLabel = NULL;
lv_obj_t * ui_BattarywarnImage = NULL;
lv_obj_t * ui_HazzardImage = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_Left0Image = NULL;
lv_obj_t * ui_Left1Image = NULL;
lv_obj_t * ui_Right0Image = NULL;
lv_obj_t * ui_Right1Image = NULL;
lv_obj_t * ui_AccImage = NULL;
lv_obj_t * ui_AccUnit = NULL;
lv_obj_t * ui_AccLabel = NULL;
lv_obj_t * ui_MpptImage = NULL;
lv_obj_t * ui_MpptLabel = NULL;
lv_obj_t * ui_MotorImage = NULL;
lv_obj_t * ui_MotorLabel = NULL;
lv_obj_t * ui_BattaryImage = NULL;
lv_obj_t * ui_BattaryLabel = NULL;
lv_obj_t * ui_TeleImage = NULL;
lv_obj_t * ui_FaultcodeLabel = NULL;
lv_obj_t * ui_RecommedImage = NULL;
lv_obj_t * ui_RecommendUnit = NULL;
lv_obj_t * ui_RecommendLabel = NULL;
lv_obj_t * ui_KustImage = NULL;
lv_obj_t * ui_info1 = NULL;
lv_obj_t * ui_info2 = NULL;
lv_obj_t * ui_info3 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_info1unit = NULL;
lv_obj_t * ui_info2unit = NULL;
lv_obj_t * ui_info3unit = NULL;
lv_obj_t * ui_FaultcodecountLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 240);
    lv_obj_set_height(ui_Panel1, 2);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -120);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 2);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 128);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 240);
    lv_obj_set_height(ui_Panel2, 2);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 45);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedUnit = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedUnit, 74);
    lv_obj_set_height(ui_SpeedUnit, 38);
    lv_obj_set_x(ui_SpeedUnit, 95);
    lv_obj_set_y(ui_SpeedUnit, -60);
    lv_obj_set_align(ui_SpeedUnit, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_SpeedUnit, "km/h");
    lv_textarea_set_placeholder_text(ui_SpeedUnit, "Placeholder...");
    lv_obj_clear_flag(ui_SpeedUnit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_SpeedUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedUnit, &ui_font_fontspeedunit, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SpeedUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SpeedUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SpeedUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SpeedUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedLabel, 120);
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedLabel, -1);
    lv_obj_set_y(ui_SpeedLabel, -73);
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "52");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpeedLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &ui_font_fontspeed, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattarywarnImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_BattarywarnImage, &ui_img_elec_warn_png);
    lv_obj_set_width(ui_BattarywarnImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattarywarnImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattarywarnImage, -80);
    lv_obj_set_y(ui_BattarywarnImage, 3);
    lv_obj_set_align(ui_BattarywarnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BattarywarnImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BattarywarnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HazzardImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_HazzardImage, &ui_img_hazzard_png);
    lv_obj_set_width(ui_HazzardImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HazzardImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HazzardImage, -80);
    lv_obj_set_y(ui_HazzardImage, -67);
    lv_obj_set_align(ui_HazzardImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HazzardImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HazzardImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TimeLabel, 97);
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 0);
    lv_obj_set_y(ui_TimeLabel, 294);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TimeLabel, "09:30");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TimeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &ui_font_fontspeedunit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left0Image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Left0Image, &ui_img_left_0_png);
    lv_obj_set_width(ui_Left0Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left0Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left0Image, -100);
    lv_obj_set_y(ui_Left0Image, -140);
    lv_obj_set_align(ui_Left0Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left0Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Left0Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Left1Image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Left1Image, &ui_img_left_1_png);
    lv_obj_set_width(ui_Left1Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left1Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left1Image, -100);
    lv_obj_set_y(ui_Left1Image, -140);
    lv_obj_set_align(ui_Left1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left1Image, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Left1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Right0Image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Right0Image, &ui_img_right_0_png);
    lv_obj_set_width(ui_Right0Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Right0Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Right0Image, 100);
    lv_obj_set_y(ui_Right0Image, -140);
    lv_obj_set_align(ui_Right0Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Right0Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Right0Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Right1Image = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Right1Image, &ui_img_right_1_png);
    lv_obj_set_width(ui_Right1Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Right1Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Right1Image, 100);
    lv_obj_set_y(ui_Right1Image, -140);
    lv_obj_set_align(ui_Right1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Right1Image, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Right1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AccImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_AccImage, &ui_img_acc_png);
    lv_obj_set_width(ui_AccImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AccImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccImage, 18);
    lv_obj_set_y(ui_AccImage, 0);
    lv_obj_set_align(ui_AccImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AccImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AccImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AccUnit = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_AccUnit, 42);
    lv_obj_set_height(ui_AccUnit, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_AccUnit, 18);
    lv_obj_set_y(ui_AccUnit, 28);
    lv_obj_set_align(ui_AccUnit, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_AccUnit, "km/h");
    lv_textarea_set_placeholder_text(ui_AccUnit, "Placeholder...");
    lv_obj_add_flag(ui_AccUnit, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_AccUnit, &ui_font_accunit, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AccUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AccUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AccUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AccUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AccUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AccLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AccLabel, 58);
    lv_obj_set_height(ui_AccLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AccLabel, -30);
    lv_obj_set_y(ui_AccLabel, 23);
    lv_obj_set_align(ui_AccLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AccLabel, "70");
    lv_obj_add_flag(ui_AccLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_AccLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AccLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AccLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AccLabel, &ui_font_acc, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MpptImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_MpptImage, &ui_img_mppt_png);
    lv_obj_set_width(ui_MpptImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MpptImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MpptImage, 80);
    lv_obj_set_y(ui_MpptImage, 77);
    lv_obj_set_align(ui_MpptImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MpptImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MpptImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MpptLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MpptLabel, 67);
    lv_obj_set_height(ui_MpptLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MpptLabel, 80);
    lv_obj_set_y(ui_MpptLabel, 260);
    lv_obj_set_align(ui_MpptLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MpptLabel, "244W");
    lv_obj_set_style_text_color(ui_MpptLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MpptLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MpptLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MpptLabel, &ui_font_fontspeedunit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_MotorImage, &ui_img_motor_png);
    lv_obj_set_width(ui_MotorImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorImage, -80);
    lv_obj_set_y(ui_MotorImage, 77);
    lv_obj_set_align(ui_MotorImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MotorImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MotorLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MotorLabel, 67);
    lv_obj_set_height(ui_MotorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorLabel, -80);
    lv_obj_set_y(ui_MotorLabel, 260);
    lv_obj_set_align(ui_MotorLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MotorLabel, "62W");
    lv_obj_set_style_text_color(ui_MotorLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MotorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorLabel, &ui_font_fontspeedunit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BattaryImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_BattaryImage, &ui_img_battary_png);
    lv_obj_set_width(ui_BattaryImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BattaryImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattaryImage, 107);
    lv_obj_set_y(ui_BattaryImage, 144);
    lv_obj_set_align(ui_BattaryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BattaryImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BattaryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BattaryLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BattaryLabel, 52);
    lv_obj_set_height(ui_BattaryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BattaryLabel, 68);
    lv_obj_set_y(ui_BattaryLabel, 294);
    lv_obj_set_align(ui_BattaryLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_BattaryLabel, "43%");
    lv_obj_set_style_text_color(ui_BattaryLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BattaryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BattaryLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BattaryLabel, &ui_font_fontspeedunit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TeleImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_TeleImage, &ui_img_commu_png);
    lv_obj_set_width(ui_TeleImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TeleImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TeleImage, -103);
    lv_obj_set_y(ui_TeleImage, 145);
    lv_obj_set_align(ui_TeleImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TeleImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TeleImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FaultcodeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FaultcodeLabel, 40);
    lv_obj_set_height(ui_FaultcodeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FaultcodeLabel, -79);
    lv_obj_set_y(ui_FaultcodeLabel, 145);
    lv_obj_set_align(ui_FaultcodeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FaultcodeLabel, "12");
    lv_obj_set_style_text_align(ui_FaultcodeLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FaultcodeLabel, &ui_font_fontspeedunit, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecommedImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_RecommedImage, &ui_img_recommend_png);
    lv_obj_set_width(ui_RecommedImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecommedImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecommedImage, 93);
    lv_obj_set_y(ui_RecommedImage, 1);
    lv_obj_set_align(ui_RecommedImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecommedImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RecommedImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RecommendUnit = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_RecommendUnit, 42);
    lv_obj_set_height(ui_RecommendUnit, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_RecommendUnit, 93);
    lv_obj_set_y(ui_RecommendUnit, 28);
    lv_obj_set_align(ui_RecommendUnit, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_RecommendUnit, "km/h");
    lv_textarea_set_placeholder_text(ui_RecommendUnit, "Placeholder...");
    lv_obj_set_style_text_font(ui_RecommendUnit, &ui_font_accunit, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RecommendUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RecommendUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RecommendUnit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecommendLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RecommendLabel, 58);
    lv_obj_set_height(ui_RecommendLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecommendLabel, 45);
    lv_obj_set_y(ui_RecommendLabel, 23);
    lv_obj_set_align(ui_RecommendLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RecommendLabel, "93");
    lv_obj_set_style_text_color(ui_RecommendLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RecommendLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RecommendLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RecommendLabel, &ui_font_acc, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KustImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_KustImage, &ui_img_logo_png);
    lv_obj_set_width(ui_KustImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KustImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KustImage, 0);
    lv_obj_set_y(ui_KustImage, -140);
    lv_obj_set_align(ui_KustImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KustImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KustImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_info1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_info1, 70);
    lv_obj_set_height(ui_info1, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_info1, -20);
    lv_obj_set_y(ui_info1, 60);
    lv_obj_set_align(ui_info1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_info1, "info1");
    lv_textarea_set_placeholder_text(ui_info1, "Placeholder...");
    lv_obj_set_style_text_font(ui_info1, &ui_font_info, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_info1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_info1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_info1, &ui_font_info, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_info2 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_info2, 70);
    lv_obj_set_height(ui_info2, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_info2, -20);
    lv_obj_set_y(ui_info2, 80);
    lv_obj_set_align(ui_info2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_info2, "info2");
    lv_textarea_set_placeholder_text(ui_info2, "Placeholder...");
    lv_obj_set_style_text_font(ui_info2, &ui_font_info, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_info2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_info2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info3 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_info3, 70);
    lv_obj_set_height(ui_info3, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_info3, -19);
    lv_obj_set_y(ui_info3, 100);
    lv_obj_set_align(ui_info3, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_info3, "info3");
    lv_textarea_set_placeholder_text(ui_info3, "Placeholder...");
    lv_obj_set_style_text_font(ui_info3, &ui_font_info, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_info3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_info3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 91);
    lv_obj_set_height(ui_Bar1, 5);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 121);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_info1unit = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_info1unit, 70);
    lv_obj_set_height(ui_info1unit, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_info1unit, 30);
    lv_obj_set_y(ui_info1unit, 60);
    lv_obj_set_align(ui_info1unit, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_info1unit, "03 %");
    lv_textarea_set_placeholder_text(ui_info1unit, "Placeholder...");
    lv_obj_set_style_text_align(ui_info1unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_info1unit, &ui_font_info, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info1unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info1unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info1unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_info1unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_info1unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info2unit = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_info2unit, 70);
    lv_obj_set_height(ui_info2unit, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_info2unit, 30);
    lv_obj_set_y(ui_info2unit, 80);
    lv_obj_set_align(ui_info2unit, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_info2unit, "08 W");
    lv_textarea_set_placeholder_text(ui_info2unit, "Placeholder...");
    lv_obj_set_style_text_align(ui_info2unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_info2unit, &ui_font_info, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info2unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info2unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info2unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_info2unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_info2unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_info3unit = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_info3unit, 70);
    lv_obj_set_height(ui_info3unit, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_info3unit, 30);
    lv_obj_set_y(ui_info3unit, 100);
    lv_obj_set_align(ui_info3unit, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_info3unit, "19 km");
    lv_textarea_set_placeholder_text(ui_info3unit, "Placeholder...");
    lv_obj_set_style_text_align(ui_info3unit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_info3unit, &ui_font_info, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info3unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info3unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_info3unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_info3unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_info3unit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FaultcodecountLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FaultcodecountLabel, 29);
    lv_obj_set_height(ui_FaultcodecountLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FaultcodecountLabel, -44);
    lv_obj_set_y(ui_FaultcodecountLabel, 142);
    lv_obj_set_align(ui_FaultcodecountLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FaultcodecountLabel, "+0");
    lv_obj_set_style_text_align(ui_FaultcodecountLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FaultcodecountLabel, &ui_font_accunit, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Panel1 = NULL;
    ui_Panel3 = NULL;
    ui_Panel2 = NULL;
    ui_SpeedUnit = NULL;
    ui_SpeedLabel = NULL;
    ui_BattarywarnImage = NULL;
    ui_HazzardImage = NULL;
    ui_TimeLabel = NULL;
    ui_Left0Image = NULL;
    ui_Left1Image = NULL;
    ui_Right0Image = NULL;
    ui_Right1Image = NULL;
    ui_AccImage = NULL;
    ui_AccUnit = NULL;
    ui_AccLabel = NULL;
    ui_MpptImage = NULL;
    ui_MpptLabel = NULL;
    ui_MotorImage = NULL;
    ui_MotorLabel = NULL;
    ui_BattaryImage = NULL;
    ui_BattaryLabel = NULL;
    ui_TeleImage = NULL;
    ui_FaultcodeLabel = NULL;
    ui_RecommedImage = NULL;
    ui_RecommendUnit = NULL;
    ui_RecommendLabel = NULL;
    ui_KustImage = NULL;
    ui_info1 = NULL;
    ui_info2 = NULL;
    ui_info3 = NULL;
    ui_Bar1 = NULL;
    ui_info1unit = NULL;
    ui_info2unit = NULL;
    ui_info3unit = NULL;
    ui_FaultcodecountLabel = NULL;

}
